"""Add active buffs table for potion effects

Revision ID: 6aadafa6ae51
Revises: 7722f7210712
Create Date: 2025-12-29 22:03:02.881735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6aadafa6ae51'
down_revision = '7722f7210712'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
