"""Add set_type column to pet_sets table

Revision ID: 9344acbba28d
Revises: 828a490a599b
Create Date: 2025-12-26 11:11:01.320515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9344acbba28d'
down_revision = '828a490a599b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Create ENUM types (skip if they already exist)
    connection = op.get_bind()

    # Check and create types
    for type_name, values in [
        ('settype', "('ATTACK', 'DEFENSE')"),
        ('itemtype', "('WEAPON', 'HELMET', 'ARMOR', 'BOOTS', 'GLOVES', 'RING', 'AMULET', 'PET_EQUIPMENT', 'CONSUMABLE')"),
        ('itemrarity', "('COMMON', 'UNCOMMON', 'RARE', 'EPIC', 'LEGENDARY')"),
        ('petspecies', "('DRAGON', 'WOLF', 'BEAR', 'FOX', 'PHOENIX', 'TIGER', 'LION', 'EAGLE', 'SERPENT', 'GRIFFIN', 'UNICORN', 'HYDRA', 'CERBERUS', 'PEGASUS', 'WYVERN', 'SPIDER', 'MYSTERY')"),
        ('petfocus', "('ATTACK', 'DEFENSE', 'HP', 'DAMAGE', 'MIXED', 'BALANCED')")
    ]:
        result = connection.execute(sa.text(f"SELECT 1 FROM pg_type WHERE typname = '{type_name}'"))
        if not result.fetchone():
            connection.execute(sa.text(f"CREATE TYPE {type_name} AS ENUM {values}"))

    # Add set_type column to pet_sets with default value
    connection.execute(sa.text("ALTER TABLE pet_sets ADD COLUMN IF NOT EXISTS set_type settype DEFAULT 'ATTACK'"))
    connection.execute(sa.text("ALTER TABLE pet_sets ALTER COLUMN set_type SET NOT NULL"))
    connection.execute(sa.text("ALTER TABLE pet_sets ALTER COLUMN set_type DROP DEFAULT"))

    # Convert existing VARCHAR columns to ENUMs using USING clause
    connection.execute(sa.text("ALTER TABLE equipment_sets ALTER COLUMN set_type TYPE settype USING set_type::settype"))
    connection.execute(sa.text("ALTER TABLE inventory_items ALTER COLUMN item_type TYPE itemtype USING item_type::itemtype"))
    connection.execute(sa.text("ALTER TABLE inventory_items ALTER COLUMN rarity TYPE itemrarity USING rarity::itemrarity"))
    connection.execute(sa.text("ALTER TABLE pets ALTER COLUMN species TYPE petspecies USING species::petspecies"))
    connection.execute(sa.text("ALTER TABLE pets ALTER COLUMN focus TYPE petfocus USING focus::petfocus"))

    # Update nullable constraints
    op.alter_column('battle_participants', 'is_dead', existing_type=sa.BOOLEAN(), nullable=True, existing_server_default=sa.text('false'))
    op.alter_column('battle_participants', 'resurrection_count', existing_type=sa.INTEGER(), nullable=True, existing_server_default=sa.text('0'))
    op.alter_column('battles', 'is_boss_raid', existing_type=sa.BOOLEAN(), nullable=True, existing_server_default=sa.text('false'))
    op.alter_column('battles', 'boss_phase_count', existing_type=sa.INTEGER(), nullable=True, existing_server_default=sa.text('3'))
    op.alter_column('battles', 'boss_current_phase', existing_type=sa.INTEGER(), nullable=True, existing_server_default=sa.text('1'))
    op.alter_column('battles', 'min_players', existing_type=sa.INTEGER(), nullable=True, existing_server_default=sa.text('1'))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pets', 'focus',
               existing_type=sa.Enum('ATTACK', 'DEFENSE', 'HP', 'DAMAGE', 'MIXED', 'BALANCED', name='petfocus'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('pets', 'species',
               existing_type=sa.Enum('DRAGON', 'WOLF', 'BEAR', 'FOX', 'PHOENIX', 'TIGER', 'LION', 'EAGLE', 'SERPENT', 'GRIFFIN', 'UNICORN', 'HYDRA', 'CERBERUS', 'PEGASUS', 'WYVERN', 'SPIDER', 'MYSTERY', name='petspecies'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('pet_sets', 'set_type')
    op.alter_column('inventory_items', 'rarity',
               existing_type=sa.Enum('COMMON', 'UNCOMMON', 'RARE', 'EPIC', 'LEGENDARY', name='itemrarity'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('inventory_items', 'item_type',
               existing_type=sa.Enum('WEAPON', 'HELMET', 'ARMOR', 'BOOTS', 'GLOVES', 'RING', 'AMULET', 'PET_EQUIPMENT', 'CONSUMABLE', name='itemtype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('equipment_sets', 'set_type',
               existing_type=sa.Enum('ATTACK', 'DEFENSE', name='settype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('battles', 'min_players',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('battles', 'boss_current_phase',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('battles', 'boss_phase_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('3'))
    op.alter_column('battles', 'is_boss_raid',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('battle_participants', 'resurrection_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('battle_participants', 'is_dead',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
