"""add_pet_species_and_base_stats

Revision ID: bedad79ccf34
Revises: c36aacd3eb6b
Create Date: 2025-12-11 14:56:42.267616

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bedad79ccf34'
down_revision = 'c36aacd3eb6b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('base_attack', sa.Integer(), nullable=True))
    op.add_column('pets', sa.Column('base_defense', sa.Integer(), nullable=True))
    op.add_column('pets', sa.Column('base_hp', sa.Integer(), nullable=True))
    op.alter_column('pets', 'species',
               existing_type=postgresql.ENUM('DRAGON', 'WOLF', 'BEAR', 'FOX', 'PHOENIX', 'TIGER', 'LION', 'EAGLE', 'SERPENT', 'GRIFFIN', 'UNICORN', 'HYDRA', 'CERBERUS', 'PEGASUS', name='petspecies'),
               nullable=True)
    op.alter_column('pets', 'focus',
               existing_type=postgresql.ENUM('ATTACK', 'DEFENSE', 'HP', 'DAMAGE', 'MIXED', 'BALANCED', name='petfocus'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pets', 'focus',
               existing_type=postgresql.ENUM('ATTACK', 'DEFENSE', 'HP', 'DAMAGE', 'MIXED', 'BALANCED', name='petfocus'),
               nullable=False)
    op.alter_column('pets', 'species',
               existing_type=postgresql.ENUM('DRAGON', 'WOLF', 'BEAR', 'FOX', 'PHOENIX', 'TIGER', 'LION', 'EAGLE', 'SERPENT', 'GRIFFIN', 'UNICORN', 'HYDRA', 'CERBERUS', 'PEGASUS', name='petspecies'),
               nullable=False)
    op.drop_column('pets', 'base_hp')
    op.drop_column('pets', 'base_defense')
    op.drop_column('pets', 'base_attack')
    # ### end Alembic commands ###
