"""Initial schema

Revision ID: e05f86adbac0
Revises: 
Create Date: 2025-12-10 17:15:42.380875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e05f86adbac0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('battles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', 'EPIC', 'LEGENDARY', name='difficultylevel'), nullable=False),
    sa.Column('wave_number', sa.Integer(), nullable=False),
    sa.Column('max_players', sa.Integer(), nullable=True),
    sa.Column('required_level', sa.Integer(), nullable=True),
    sa.Column('stamina_cost', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('WAITING', 'IN_PROGRESS', 'COMPLETED', 'ABANDONED', name='battlestatus'), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('gold_reward', sa.BigInteger(), nullable=True),
    sa.Column('exp_reward', sa.BigInteger(), nullable=True),
    sa.Column('loot_table', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_battles_id'), 'battles', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('battle_enemies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('battle_id', sa.Integer(), nullable=False),
    sa.Column('enemy_type', sa.Enum('GOBLIN', 'ORC', 'TROLL', 'LIZARDMAN', 'DEMON', 'DRAGON', 'UNDEAD', name='enemytype'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('hp_max', sa.BigInteger(), nullable=False),
    sa.Column('hp_current', sa.BigInteger(), nullable=False),
    sa.Column('attack', sa.Integer(), nullable=False),
    sa.Column('defense', sa.Integer(), nullable=False),
    sa.Column('is_defeated', sa.Boolean(), nullable=True),
    sa.Column('defeated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['battle_id'], ['battles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_battle_enemies_id'), 'battle_enemies', ['id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('exp', sa.BigInteger(), nullable=True),
    sa.Column('exp_max', sa.BigInteger(), nullable=True),
    sa.Column('gold', sa.BigInteger(), nullable=True),
    sa.Column('gems', sa.Integer(), nullable=True),
    sa.Column('stamina', sa.Integer(), nullable=True),
    sa.Column('stamina_max', sa.Integer(), nullable=True),
    sa.Column('base_attack', sa.Integer(), nullable=True),
    sa.Column('base_defense', sa.Integer(), nullable=True),
    sa.Column('base_hp', sa.Integer(), nullable=True),
    sa.Column('unspent_stat_points', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_stamina_regen', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    op.create_index(op.f('ix_players_username'), 'players', ['username'], unique=True)
    op.create_table('battle_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('battle_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('total_damage_dealt', sa.BigInteger(), nullable=True),
    sa.Column('attacks_count', sa.Integer(), nullable=True),
    sa.Column('has_claimed_loot', sa.Boolean(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('rewards', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['battle_id'], ['battles.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_battle_participants_id'), 'battle_participants', ['id'], unique=False)
    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.Enum('WEAPON', 'HELMET', 'ARMOR', 'BOOTS', 'GLOVES', 'RING', 'AMULET', 'PET_EQUIPMENT', 'CONSUMABLE', name='itemtype'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rarity', sa.Enum('COMMON', 'UNCOMMON', 'RARE', 'EPIC', 'LEGENDARY', name='itemrarity'), nullable=False),
    sa.Column('level_requirement', sa.Integer(), nullable=True),
    sa.Column('attack_bonus', sa.Integer(), nullable=True),
    sa.Column('defense_bonus', sa.Integer(), nullable=True),
    sa.Column('hp_bonus', sa.Integer(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_items_id'), 'inventory_items', ['id'], unique=False)
    op.create_table('shop_purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('cost_gold', sa.BigInteger(), nullable=True),
    sa.Column('cost_gems', sa.Integer(), nullable=True),
    sa.Column('purchased_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_purchases_id'), 'shop_purchases', ['id'], unique=False)
    op.create_table('equipment_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('set_type', sa.Enum('ATTACK', 'DEFENSE', name='settype'), nullable=False),
    sa.Column('weapon_id', sa.Integer(), nullable=True),
    sa.Column('helmet_id', sa.Integer(), nullable=True),
    sa.Column('armor_id', sa.Integer(), nullable=True),
    sa.Column('boots_id', sa.Integer(), nullable=True),
    sa.Column('gloves_id', sa.Integer(), nullable=True),
    sa.Column('ring_id', sa.Integer(), nullable=True),
    sa.Column('ring2_id', sa.Integer(), nullable=True),
    sa.Column('amulet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['amulet_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['armor_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['boots_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['gloves_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['helmet_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['ring2_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['ring_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['weapon_id'], ['inventory_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_sets_id'), 'equipment_sets', ['id'], unique=False)
    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('species', sa.Enum('DRAGON', 'WOLF', 'BEAR', 'FOX', 'PHOENIX', 'TIGER', 'LION', 'EAGLE', 'SERPENT', 'GRIFFIN', 'UNICORN', 'HYDRA', 'CERBERUS', 'PEGASUS', name='petspecies'), nullable=False),
    sa.Column('focus', sa.Enum('ATTACK', 'DEFENSE', 'HP', 'DAMAGE', 'MIXED', 'BALANCED', name='petfocus'), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('exp', sa.Integer(), nullable=True),
    sa.Column('exp_max', sa.Integer(), nullable=True),
    sa.Column('attack_bonus', sa.Integer(), nullable=True),
    sa.Column('defense_bonus', sa.Integer(), nullable=True),
    sa.Column('hp_bonus', sa.Integer(), nullable=True),
    sa.Column('attack_equip_1', sa.Integer(), nullable=True),
    sa.Column('attack_equip_2', sa.Integer(), nullable=True),
    sa.Column('attack_equip_3', sa.Integer(), nullable=True),
    sa.Column('defense_equip_1', sa.Integer(), nullable=True),
    sa.Column('defense_equip_2', sa.Integer(), nullable=True),
    sa.Column('defense_equip_3', sa.Integer(), nullable=True),
    sa.Column('is_egg', sa.Boolean(), nullable=True),
    sa.Column('hatched_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attack_equip_1'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['attack_equip_2'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['attack_equip_3'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['defense_equip_1'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['defense_equip_2'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['defense_equip_3'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pets_id'), 'pets', ['id'], unique=False)
    op.create_table('pet_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('set_type', sa.Enum('ATTACK', 'DEFENSE', name='settype'), nullable=False),
    sa.Column('pet_1_id', sa.Integer(), nullable=True),
    sa.Column('pet_2_id', sa.Integer(), nullable=True),
    sa.Column('pet_3_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pet_1_id'], ['pets.id'], ),
    sa.ForeignKeyConstraint(['pet_2_id'], ['pets.id'], ),
    sa.ForeignKeyConstraint(['pet_3_id'], ['pets.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pet_sets_id'), 'pet_sets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pet_sets_id'), table_name='pet_sets')
    op.drop_table('pet_sets')
    op.drop_index(op.f('ix_pets_id'), table_name='pets')
    op.drop_table('pets')
    op.drop_index(op.f('ix_equipment_sets_id'), table_name='equipment_sets')
    op.drop_table('equipment_sets')
    op.drop_index(op.f('ix_shop_purchases_id'), table_name='shop_purchases')
    op.drop_table('shop_purchases')
    op.drop_index(op.f('ix_inventory_items_id'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_battle_participants_id'), table_name='battle_participants')
    op.drop_table('battle_participants')
    op.drop_index(op.f('ix_players_username'), table_name='players')
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_battle_enemies_id'), table_name='battle_enemies')
    op.drop_table('battle_enemies')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_battles_id'), table_name='battles')
    op.drop_table('battles')
    # ### end Alembic commands ###
